package com.myorg.losrules.q98000;

import com.myorg.losmodel.model.ValidateQuestionRequest;
import com.myorg.losmodel.model.client.PBEntityClient;
import com.myorg.losmodel.model.client.PBIndividualClient;
import com.myorg.losmodel.util.ModelUtils;

rule "the interest rate"
when
    ValidateQuestionRequest(questionId == 98000,
        mortgageApplication.mtgDetails.loanDetails.interestRate != 0.0)
then
    System.out.println("Interest rate");
    ModelUtils.addQnsIdToEnableList(99000);
end
    

