package com.myorg.losrules.q26000;

import com.myorg.losmodel.model.ValidateQuestionRequest;
import com.myorg.losmodel.model.client.PBEntityClient;
import com.myorg.losmodel.model.client.PBIndividualClient;
import com.myorg.losmodel.util.ModelUtils;

rule "uniqueIdentifierType is required"
when 
    ValidateQuestionRequest((questionId == 26000 || questionId == null) &&
        mortgageApplication.entityClient != null &&
        mortgageApplication.entityClient.uniqueIdentifierType == null);
then
    System.out.println("uniqueIdentifierType is required");
    
    ModelUtils.addMesgToValidationMesgList("error" , "Client Identifier Type cannot be blank");
    
end

rule "uniqueIdentifier is required"
when 
    ValidateQuestionRequest((questionId == 26000 || questionId == null) &&
        mortgageApplication.entityClient != null &&
        mortgageApplication.entityClient.uniqueIdentifier == null);
then
    System.out.println("uniqueIdentifier is required");
    
    ModelUtils.addMesgToValidationMesgList("error" , "Client Identifier cannot be blank");
    
end

rule "uniqueIdentifier proper format"
when 
  $v : ValidateQuestionRequest((questionId == 26000 || questionId == null) &&
        mortgageApplication.entityClient != null &&
        mortgageApplication.entityClient.uniqueIdentifierType == "SSN" &&
        mortgageApplication.entityClient.uniqueIdentifier not matches "^(?!000|666)[0-8][0-9]{2}-(?!00)[0-9]{2}-(?!0000)[0-9]{4}$");
then
    System.out.println("uniqueIdentifier is required" + $v.getMortgageApplication().getEntityClient().getUniqueIdentifier());
    
    ModelUtils.addMesgToValidationMesgList("error" , "Invalid SSN or not in proper format");
    
end